Locations = [
    {"State": "Andhra Pradesh", "City": "Amaravati", "Latitude": 16.5, "Longitude": 80.5},
    {"State": "Arunachal Pradesh", "City": "Itanagar", "Latitude": 27.1, "Longitude": 93.6},
    {"State": "Assam", "City": "Dispur", "Latitude": 26.2, "Longitude": 91.8},
    {"State": "Bihar", "City": "Patna", "Latitude": 25.6, "Longitude": 85.1},
    {"State": "Chhattisgarh", "City": "Raipur", "Latitude": 21.2, "Longitude": 81.6},
    {"State": "Goa", "City": "Panaji", "Latitude": 15.5, "Longitude": 73.8},
    {"State": "Gujarat", "City": "Gandhinagar", "Latitude": 23.2, "Longitude": 72.7},
    {"State": "Haryana", "City": "Chandigarh", "Latitude": 30.7, "Longitude": 76.8},
    {"State": "Himachal Pradesh", "City": "Shimla", "Latitude": 31.1, "Longitude": 77.2},
    {"State": "Jharkhand", "City": "Ranchi", "Latitude": 23.3, "Longitude": 85.3},
    {"State": "Karnataka", "City": "Bengaluru", "Latitude": 12.9, "Longitude": 77.6},
    {"State": "Kerala", "City": "Thiruvananthapuram", "Latitude": 8.5, "Longitude": 76.9},
    {"State": "Madhya Pradesh", "City": "Bhopal", "Latitude": 23.3, "Longitude": 77.4},
    {"State": "Maharashtra", "City": "Mumbai", "Latitude": 19.1, "Longitude": 72.9},
    {"State": "Manipur", "City": "Imphal", "Latitude": 24.8, "Longitude": 93.9},
    {"State": "Meghalaya", "City": "Shillong", "Latitude": 25.6, "Longitude": 91.9},
    {"State": "Mizoram", "City": "Aizawl", "Latitude": 23.7, "Longitude": 92.7},
    {"State": "Nagaland", "City": "Kohima", "Latitude": 25.7, "Longitude": 94.1},
    {"State": "Odisha", "City": "Bhubaneswar", "Latitude": 20.2, "Longitude": 85.8},
    {"State": "Punjab", "City": "Chandigarh", "Latitude": 30.7, "Longitude": 76.8},
    {"State": "Rajasthan", "City": "Jaipur", "Latitude": 26.9, "Longitude": 75.8},
    {"State": "Sikkim", "City": "Gangtok", "Latitude": 27.3, "Longitude": 88.5},
    {"State": "Tamil Nadu", "City": "Chennai", "Latitude": 13.0, "Longitude": 80.3},
    {"State": "Telangana", "City": "Hyderabad", "Latitude": 17.4, "Longitude": 78.5},
    {"State": "Tripura", "City": "Agartala", "Latitude": 23.8, "Longitude": 91.3},
    {"State": "Uttarakhand", "City": "Dehradun", "Latitude": 30.3, "Longitude": 78.0},
    {"State": "Uttar Pradesh", "City": "Lucknow", "Latitude": 26.8, "Longitude": 80.9},
    {"State": "West Bengal", "City": "Kolkata", "Latitude": 22.6, "Longitude": 88.4}
]
